server:
  port: 1200
spring:
  application:
    name: tech-trekker
  datasource:
    url: "jdbc:mysql://localhost/blog"
    username: "root"
    password:  "root"
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

upload:
  file:
    profile: "profile_images"
    blog:
      banner: "blog_banner_images"        